### ISSUE TITLE
How to use the package just by adding it to pubspec.yaml

### ISSUE THREAD

**Issue by ewertonrfd** [selvam920/drago_pos_printer#5]
All good?

How do I add the package to pubspec.yaml and use direct printing to USB?
Because running the example works
But just adding the package doesn't work, I saw that the example uses specific versions

I would like to just add the package and have printing via USB working, I'm trying some possibilities here, but I haven't achieved anything yet

Att

**Comment by selvam920** [comment]
Use like below in pubspec.yaml
drago_pos_printer:
   git:
      url: https://github.com/selvam920/drago_pos_printer.git
